### ISSUE TITLE
ReadAsync regression

### ISSUE THREAD

**Issue by leecannon** [vb-consulting/Norm.net#1]
Prior versions of this library supported ReadAsync called with these generic parameters:
```c#
ReadAsync<string, TimeSpan?, TimeSpan?, string, bool>(sql)
```
But with newer versions this throws:
```
Norm.NormMultipleMappingsException: Multiple mappings requires types of same category:
    Classes with classes, records with records, value tuples with value tuple and simple types with simple types.
    For example pappings `Read<Class, int>` or `Read<int, Class>` are not permitted.
```

**Comment by vbilopav** [comment]
That exception meant to prevent mapping like this `ReadAsync<string, Class>(sql)` which is not supported.

However, it seems that .NET handles `TimeSpan` types a bit differently (there is no `TypeCode` unlike `DateTime`), so I had to fix that.

Package version 3.1.1. with this fix is being built and deployed at this moment.

I added a unit test for this issue: https://github.com/vb-consulting/Norm.net/blob/be6c564f202994204ff5f020708b38c0f171b7c6/Tests/PostgreSqlUnitTests/ReadTuplesUnitTests.cs#L394

Also, support for instance mapping for TimeSpan has been added with the test also:
https://github.com/vb-consulting/Norm.net/blob/be6c564f202994204ff5f020708b38c0f171b7c6/Tests/PostgreSqlUnitTests/QueryUnitTests.cs#L303
