### ISSUE TITLE
Stripping underscores from column names

### ISSUE THREAD

**Issue by jmurphy-asurity** [vb-consulting/Norm.net#15]
If I do `var record in conn.ReadAsync<dynamic>("select 1 as test_test)` the column name `test_test` will be converted to expando key `testtest`, I think due to [this](https://github.com/vb-consulting/Norm.net/blob/b43890ea12b6f3b957e0f2416784a8f5e3011c61/Norm/Mapper/TypeCache.cs#L99).  Is there a reason to remove the underscores?

**Comment by vbilopav** [comment]
Yes, dotnet naming convention I believe. I wanted to map field_name to FieldName.

I'll create a new version tomorrow for you with the global option to preserve underscores if you want.

**Comment by vbilopav** [comment]
Here are the release notes:
https://github.com/vb-consulting/Norm.net/blob/master/changelog.md#534-2023-05-26

Also, thanks to this issue, I've found some missed performance optimization issues that are now fixed, tested, and merged.

Thank you for helping me improve this library.
