### ISSUE TITLE
Suggestion: Passing parameters with IDictionary

### ISSUE THREAD

**Issue by goncalo-oliveira** [vb-consulting/Norm.net#18]
Hi,

I have a scenario where the parameters for a query/command are created dynamically. This means that, in order to use the object mapping functionality such as the one below is not possible out of the box.

```csharp
connection.Read<T>( "select @p0, @p1", new { p0 = "value1", p1 = "value2" } );
```

To get around this issue, I am doing some nasty things that essentially turns a `IDictionary<string, object?>` into an anonymous type.

It would be a great addition if we could construct a `IDictionary<string, object?>` and use that as the `parameters` argument.

```csharp
connection.Read<T>( "select @p0, @p1", new Dictionary<string, object>
{
    { "p0", 1 },
    { "p1", "2" }
} ); 
```

**Comment by goncalo-oliveira** [comment]
Actually... it seems that a workaround is actually constructing a list of `SqlParameter` instances.

```csharp
var parameters = dictionary.Select( p => new SqlParameter( p.Key, p.Value ) ).ToArray()
```

**Comment by goncalo-oliveira** [comment]
I'm leaving this open to see what you think about it. It's definitely possible to work around with the [above](https://github.com/vb-consulting/Norm.net/issues/18#issuecomment-1662565392) code, but I wonder if there's a *cleaner* way.

Again, this is not the typical scenario and most likely affecting less than 1% of the target users.

**Comment by vbilopav** [comment]
You can use tuples for parameters like this
https://github.com/vb-consulting/Norm.net/blob/master/Tests/PostgreSqlUnitTests/ParametersUnitTests.cs#L133

Or you can use anonymous object like this
https://github.com/vb-consulting/Norm.net/blob/master/Tests/PostgreSqlUnitTests/ParametersUnitTests.cs#L192C3-L192C3

Anonymous object can be set as second parametar in a read method.

See that unit test for various examples of using parameters.

**Comment by vbilopav** [comment]
I looked around this issue a bit.

You can use `WithParameters` extension method to:

1) Send `DbParameter` type parameters object like this:

```csharp
using var connection = new SqlConnection(fixture.ConnectionString);
var (s, i, b, d) = connection
    .WithParameters(
        new SqlParameter("s", "str"),
        new SqlParameter("i", 999),
        new SqlParameter("b", true),
        new SqlParameter("d", new DateTime(1977, 5, 19)))
    .Read<string, int, bool, DateTime>("select @s, @i, @b, @d")
    .Single();
```

See more at:

2) Send a param array of two-.value tuples - where the first value is a parameter value and the second is database type:

```csharp
using var connection = new SqlConnection(fixture.ConnectionString);
var (s, i, b, d, @null) = connection
    .WithParameters(
        ("str", DbType.String), 
        (999, DbType.Int32), 
        (true, DbType.Boolean), 
        (new DateTime(1977, 5, 19), DbType.Date), 
        ((string)null, DbType.String))
    .Read<string, int, bool, DateTime, string>("select $1, $2, $3, $4, $5")
    .Single();
```

You can do that with database provider-specific database types, such as `NpgsqlDbType` for Postgres or  `SqlDbType` for SQL Server.,

3) Use an anonymous object parameter where values are  either:
- `DbParameter` type.

```csharp
var strValue = "str";
using var connection = new NpgsqlConnection(fixture.ConnectionString);
var (s, i, b, d, @null) = connection
    .WithParameters(new
    {
        strValue = new NpgsqlParameter("StrValue", strValue),
    })
    .Read<string, int, bool, DateTime, string>("select @StrValue")
    .Single();
```

Note: in this case, the parameter name is taken from the  `DbParameter` instance.

- Tuple valuer and specific DB provider type:

```csharp
var (i, j) = connection
    .WithParameters(new
    {
        i = (1, NpgsqlDbType.Integer),
        j = ("{\"test\": \"value\"}", NpgsqlDbType.Json)
    })
    .Read<int, string>("select @i, @j->>'test'")
    .Single();
```

Note: works the same with generic `SqlType` parameter or DB-specific db type parameter such as `SqlDbType` for SQL Server.


Also, when using the anonymous object for parameters, you can pass that object as the second parameter after the SQL string, which allows you to skip the `WithParameters` method:


```csharp
var (i, j) = connection
    .Read<int, string>("select @i, @j->>'test'", new
    {
        i = (1, NpgsqlDbType.Integer),
        j = ("{\"test\": \"value\"}", NpgsqlDbType.Json)
    })
    .Single();
```

```csharp
var strValue = "str";
using var connection = new NpgsqlConnection(fixture.ConnectionString);
var (s, i, b, d, @null) = connection
    .Read<string, int, bool, DateTime, string>("select @StrValue", new
    {
        strValue = new NpgsqlParameter("StrValue", strValue),
    })
    .Single();
```

You can also mix various parameter styles (positional and named), etc...

You can see more in this unit tests:
https://github.com/vb-consulting/Norm.net/blob/master/Tests/PostgreSqlUnitTests/ParametersUnitTests.cs


I'm not sure what problem exactly I would dictionary solve, so I suggest closing this issue and moving to discussion board.

**Comment by goncalo-oliveira** [comment]
Hi @vbilopav,

Apologies for the late reply, been quite busy lately.

Yeah, I agree the issue can be closed. I already had a workaround [here](https://github.com/vb-consulting/Norm.net/issues/18#issuecomment-1662565392) which is one of the solutions you proposed.

I don't think it's worth doing the work to take in the dictionary as suggested. It's an edge case and the workaround works perfectly well.

Thanks for taking the time to look at it.
