### ISSUE TITLE
How to get the number of affected rows？

### ISSUE THREAD

**Issue by freelensman** [vb-consulting/Norm.net#22]
Using Execute does not return the number of rows affected, How to get the number of affected rows？

for example:
connection.Execute("INSERT IGNORE INTO OrderDetails (id) values (@id)",new {id= "333"});

**Comment by vbilopav** [comment]
If you mean a property on a reader object, it's not exposed yet.

Depending on a database provider I usually do another select to return number of rows affected. For exemple on SQL Server it's something like SELECT @@ROWCOUNT or similar, on PostgreSQL it's different, look it up.

I could release a new version where execute methods would return rows affected property from a reader object... But again Execute doesn't use reader object, ... Let me get back to you on this.

**Comment by vbilopav** [comment]
I'll add another property and release a new version (hopefully today) called `RowsAffected` that will have a 
- return value from `ExecuteNonQuery` call if it was a simple `Execute`
or
- value of `RowsAffected` from `DbReade` for `Read` operations

I'll let you know when it is released.

**Comment by freelensman** [comment]
This will make it a lot easier, thank you very much!
