### ISSUE TITLE
Expand support for custom types

### ISSUE THREAD

**Issue by bondehagen** [vb-consulting/Norm.net#4]
Is there a way to expand the object mapper with custom types?
I'm currently using an external object that use `DateTimeOffset` on one of the properties, which is not among the basic supported types. I can't seem to find a way to work around that without mapping the object manually. For large objects that's a a bit unfortunate.

**Comment by bondehagen** [comment]
And it should probably ignore the properties it can't match instead of throwing an exception. In that case I could have made an additional record type to map the last properties that was ignored to types that work and then do the conversion later (like `Read<ExternalObjectICantChange, PropertiesThatWorkHack>()`).

Anyway the best would be to be able to ignore some properties and add a custom delegate to convert spesific properties using a propertyname selector.

**Comment by vbilopav** [comment]
I'm not sure what exactly you mean.

Currently, mapping to `TimeSpan` from PostgreSQL `interval` type works fine:
https://github.com/vb-consulting/Norm.net/blob/be6c564f202994204ff5f020708b38c0f171b7c6/Tests/PostgreSqlUnitTests/QueryUnitTests.cs#L303

From what type you're trying to map to `DateTimeOffset`?

Afaik `DateTimeOffset` is struct that holds one `TimeSpan` value and one `DateTime` value. 
So, maybe you could do something like this:

```csharp
connection.Read<MyType>(sql).Select(x => x.MyDateTimeOffset = new DateTimeOffset(x.MyDateTime, x.MyTimespan).ToList();
```

Note that neither the `Read` nor `Select` will trigger the read or enumeration operations, so it is basically just like mapping (no perf. penalty). 
Read and Enumeration will execute on `ToList` in this example. And whatever you might have mapped before in that `MyDateTimeOffset` is overridden in that `Select` expression.


Do you have any better suggestions on how to do custom mapping so I can publish a new version?

**Comment by vbilopav** [comment]
> Anyway the best would be to be able to ignore some properties and add a custom delegate to convert spesific properties using a propertyname selector.

I'll fix this, thanks.

**Comment by vbilopav** [comment]
I'm sorry, I still don't quite understand. 

If you have a class property that is not matched by the mapper, there is no exception in my test. It just has a default value. Here is the test:

https://github.com/vb-consulting/Norm.net/blob/master/Tests/PostgreSqlUnitTests/MapUnitTests.cs#L230

Test class:

```csharp
        class TestClass
        {
            public int Id { get; init; }
            public string Foo { get; init; }
            public DateTime Day { get; init; }
            public bool? Bool { get; init; }
            public string Bar { get; init; }
        }
```

The query doesn't return bar so, Bar property is always null:

```
            var result = connection.Read<TestClass>(@"
                            select *
                            from (
                            values 
                                (1, 'foo1', '1977-05-19'::date, true),
                                (2, 'foo2', '1978-05-19'::date, false),
                                (3, 'foo3', '1979-05-19'::date, null)
                            ) t(id, foo, day, bool)").ToList();

            
            Assert.Equal(3, result.Count);

            // TestClass.Bar is not mapped, it is always default (null)
            Assert.Null(result[0].Bar);
            Assert.Null(result[0].Bar);
            Assert.Null(result[0].Bar);
```

Could you send me more information about your use case so I can re-create the issue?

Thanks

**Comment by bondehagen** [comment]
The object I was mapping is [IdentityUser<TKey>.LockoutEnd](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.entityframeworkcore.identityuser-4.lockoutend?view=aspnetcore-1.1#Microsoft_AspNetCore_Identity_EntityFrameworkCore_IdentityUser_4_LockoutEnd), so something like `public record TestRecord(DateTimeOffset? LockoutEnd)` would trigger the exception.

I didn't think about the fact that `Read` did not execute, so using a `Select` before I execute give me an opportunity to work around it, so that's great.

I like the philiosophy of this framework, so keep up the good work.
Thank you for getting back to me!

**Comment by vbilopav** [comment]
Hi, @bondehagen ,

It would be helpful to know what exact type on the database side LockoutEnd and what type of database are you using.

I've written a test for your use case and you can see here how easy is to map to anything you want by using a Linq `Select` exetnsion:
https://github.com/vb-consulting/Norm.net/blob/master/Tests/PostgreSqlUnitTests/MapUnitTests.cs#L255

I tried to add correct mapping to `DateTimeOffset` type but I was unable to. Perhaps, because I tried to map PostgreSQL `timestamp`.

If this example I provided above helps you, I would like to close this Issue, and I'll open a new one to implement correct mapping for the  `DateTimeOffset` offset.

**Comment by bondehagen** [comment]
I used same as you, timestamp with postgresql. The example helps, thank you.

**Comment by vbilopav** [comment]
Hi @bondehagen 

I've released a new version with `DateTimeOffset` support. 

You can see release notes [here](https://github.com/vb-consulting/Norm.net/blob/master/CHANGES.md#330)

Sorry that it took so long to add the `DateTimeOffset` support.

Regards,

Vedran
