### ISSUE TITLE
Support for custom types mapping

### ISSUE THREAD

**Issue by fvoncina** [vb-consulting/Norm.net#5]
Hi there!

Are you planning to add support for custom types? like the [SqlMapper.TypeHandler](https://github.com/DapperLib/Dapper/blob/main/Dapper/SqlMapper.TypeHandler.cs) in Dapper?

thanks!

**Comment by vbilopav** [comment]
I'll investigate how it could be done and what would it take and get back here asap.

**Comment by vbilopav** [comment]
Hi,

You can do custom mappings by using `Select` Linq extensions. 

That's what I do.



For example, you can read tuples and map them to any type of instance with any kind of custom mapping like this.

Let's say we have a test class that we want to map to: 


```csharp
class TestClass
{
    public int Id { get; init; }
    public string Foo { get; init; }
    public DateTime Day { get; init; }
    public bool? Bool { get; init; }
    public string Bar { get; init; }
}
```

Custom mapping for tuple values would look like this:

```csharp
var result1 = connection
    .Read<int, string, DateTime, bool?, string>(Query)
    .Select(t =>
    {
        // custom mapping here
        return new TestClass
        {
            Id = t.Item1,
            Foo = t.Item2,
            Day = t.Item3,
            Bool = t.Item4,
            Bar = t.Item5
        };
    }).ToList();
```

or, if you prefer named tuples, you can do this:

```csharp
var result2 = connection
    .Read<(int i, string f, DateTime d, bool? b1, string b2)>(Query)
    .Select(t =>
    {
        // custom mapping here
        return new TestClass
        {
            Id = t.i,
            Foo = t.f,
            Day = t.d,
            Bool = t.b1,
            Bar = t.b2
        };
    }).ToList();
```

Not that this will not trigger extra data iteration over the results, so it is quite efficient.

However, not sure does this helps.

And I'm also aware that is not quite the same as having a global mapping mechanism in `SqlMapper.TypeHandler` style, where you can register certain types for a custom mapping.

I can see how that could be implemented quite easily, but that would be a completely new feature.

Do you have a need for such a global type mapper or is this custom mapping with the `Select` method sufficient?

If it is urgent and something you could use, I can add it over this weekend and release a new version.

**Comment by vbilopav** [comment]
Edit:

You can also use `Read` extension without any generic parameters for this purpose:

`Read` extension without any generic parameters returns an array for each record with value tuples `IEnumerable<(string name, object value)[]> Read(this DbConnection connection, string command)`.

So now, you can do custom mapping like this:

```csharp
var result3 = connection
    .Read(Query)
    .Select(t =>
    {
        // custom mapping here
        return new TestClass
        {
            Id = (int)t[0].value,
            Foo = (string)t[1].value,
            Day = (DateTime)t[2].value,
            Bool = (bool?)t[3].value,
            Bar = (string)t[4].value
        };
    }).ToList();
```

Or, if you prefer to access values by name, rather than by index, you can do this (although there is a more efficient way to write this):

```csharp
var result4 = connection
    .Read(Query)
    .Select(t =>
    {
        // custom mapping here
        return new TestClass
        {
            Id = (int)t.First(t => t.name == "id").value,
            Foo = (string)t.First(t => t.name == "foo").value,
            Day = (DateTime)t.First(t => t.name == "day").value,
            Bool = (bool?)t.First(t => t.name == "bool").value,
            Bar = (string)t.First(t => t.name == "bar").value
        };
    }).ToList();
```

**Comment by vbilopav** [comment]
Edit 2:

expanding on my previous answer:

Since non-generic `Read` extension returns `IEnumerable<(string name, object value)[]>` (and `ReadAsync` returns `IAsyncEnumerable<(string name, object value)[]>`) - you can easily write an extension method that you can use globally. For example:

```csharp
public static class MappingExtensions
{
    public static TestClass MyCustomMapping(this IEnumerable<(string name, object value)[]> values)
    {
        // mapping here
        return new TestClass();
    }
}
```

and reuse it in your code like this:

```csharp
var result = connection.Read(Query).MyCustomMapping().ToList();
```

**Comment by fvoncina** [comment]
Hi, thanks for the answer.

I think it will be nice to have a way to globally inject custom type mappers so we can fully use POCOs without having to project from a tuple and then create the right POCO, specially useful for types like `Guid` or the types in postgis. 

Look at this sample, I have this POCO and table:

```sql
CREATE TABLE test1 (id uuid, title character varying(50), location geometry)
```

```csharp
public class Poco3
{
    public Guid Id { get; set; }
    public string Title { get; set; }
    public Point Location { get; set; } // from NetTopologySuite
}
```

If I want to get that record:
```csharp
var record = db.Read<Poco3>(sql).Single();
```

The following exception is raised at [this line](https://github.com/vb-consulting/Norm.net/blob/master/Norm/Extensions/ObjectMappperInternal.cs#L160):
```csharp
System.NotImplementedException: TypeCode Object not implemented
   at Norm.NormExtensions.CreateDelegate[T](PropertyInfo property, Boolean nullable)
```

The method [CreateDelegate<T>(PropertyInfo property, bool nullable)](https://github.com/vb-consulting/Norm.net/blob/master/Norm/Extensions/ObjectMappperInternal.cs#L104) doesn't know how to treat Guid or the Point type.

I can get around it by projecting from tuples like this:
```csharp
var record = db.Read<(Guid Id, string Title, Point Location)>(sql)
                .Select(dbRecord => new Poco3
                {
                    Id = dbRecord.Id,
                    Title = dbRecord.Title,
                    Location = dbRecord.Location
                })
                .Single();
```

But is cumbersome and limits you to 12 columns.

Thanks and great work

**Comment by vbilopav** [comment]
Hi,

you can use the non-generic `Read` method to avoid those issues.

The non-generic `Read` method yields enumerator of `(string name, object value)[]` array of tuples,m where `name` contains a field name and value holds an object value of whatever type the reader has returned the database.

Also, the non-generic `Read` method does not have any limitation in the number of fields.

I've created an example of custom mapping for you, you can see it here:
https://github.com/vb-consulting/Norm.net/blob/master/Tests/PostgreSqlUnitTests/CustomMappingsUnitTests.cs

In a nutshell, PG returns a single record with 14 UUID values. 

They are all mapped correctly to a large class that has 14 `Guid` types - (GuidId1 to GuidId14) and also 14 string types (StringId1 to StringId14) that are string equivalents of those Guid types.

Custom mapping class looks like this:

```csharp
public static class MappingExtensions
{
    public static IEnumerable<BigGuidClass> BigGuidCustomMapping(this IEnumerable<(string name, object value)[]> values)
    {
        foreach (var value in values)
        {
            yield return new BigGuidClass
            {
                GuidId1 = (Guid)value[0].value,
               //...
                GuidId14 = (Guid)value[13].value,

                StringId1 = value[0].value.ToString(),
                //...
                StringId14 = value[13].value.ToString(),
            };
        }
    }
}
```

Usage for this custom mapping looks like this:

```csharp
var result = connection
    .Read(@"select 
        uuid_generate_v4() id1,
        //...
        uuid_generate_v4() id14")
    .BigGuidCustomMapping()
    .First();
```

I will also now add a native UUID/Guid mapping support and release a new version.

Also, I'm not sure how I could make a custom mapping interface more elegant than this example with extension class above. 

Perhaps something like this:

```csharp
NormMapping.AddCustomType<TestClass>((string name, object value)[] row => 
{
    // custom mapping here
    return new TestClass();
});
```

This way, there is no need for an extra mapping class and you can register your class with a mapping handler.

I could also add few overloads, for example, if you don't field need names.

```csharp
NormMapping.AddCustomType<TestClass>(object[] row =>
{
    // custom mapping here
    return new TestClass();
});
```

Or if you want to index field by name:

```csharp
NormMapping.AddCustomType<TestClass>(object IDictionary<string, object> row =>
{
    // custom mapping here
    return new TestClass();
});
```

**Comment by vbilopav** [comment]
And while I'm at it, I could try adding PostGIS mappings natively so that you don't have to do custom mappings at all.

**Comment by vbilopav** [comment]
Hi,

two things:

1) Implementation of PostGIS types proves to be more challenging than I thought. I'll leave that to a new version, and perhaps, if you have some time and are willing to help me with that, that would be awesome.

2) I released a new version with GUID support and Globalč Mapper support as well. Here are the release notes:
https://github.com/vb-consulting/Norm.net/blob/master/CHANGES.md#331

Let me know if I can close this issue.

Thanks

**Comment by vbilopav** [comment]
Closing this issue since requested feature has been implemented.
