### ISSUE TITLE
Norm+pg+Identity

### ISSUE THREAD

**Issue by rkaule** [vb-consulting/Norm.net#6]
I pulled your NormPgIdentity code, set the database up, did the migrations,  then ran the program.  Everything worked as published.  I was very happy because I am no fan of EF.    I started a new project,  set it to botnet Core 5 and c# 9.  Pulled the packages (latest ones), Norm.net/3.3.1, Npgsql/6.0.0=preiview, System.Linq.Async/5.0.0 and AspNetCore.Identity.UI/45.0.8.

I had to change UserStore and RoleStore to get the IDE to stop complaining.  There were a couple other small items that I fixed.  Ran the program.  I was able to register a user.  The data ended up correct in the database.  All was good.  However when I go to login I get an exception "InvalidCastException: Can't cast database type bigint to IdentityUser`1".  It happens in the FindAsync function.   This is what I changed it to:

 private async Task<IdentityUser<long>> FindAsync(CancellationToken cancellationToken, long? userId = null, string name = null, string email = null) =>
            await _connection.WithCancellationToken(cancellationToken).ReadAsync<IdentityUser<long>>($@"
                
                select
                    {GetUserSelectRecord()}

                from
                    ""user"" u

                where
                    ( @id is null or u.id = @id ) and 
                    ( @name is null or u.normalized_user_name = @name ) and 
                    ( @email is null or u.normalized_email = @email )
            
            ", ("id", userId, DbType.Int64), ("name", name, DbType.String), ("email", email, DbType.String))
                .FirstOrDefaultAsync(cancellationToken);

Did I not correct the above function correctly?

Thanks,
Bob

**Comment by vbilopav** [comment]
The `bigint` type usually maps to the `long` type.

If I remember correctly, `IdentityUser` can set the Id type by generic and it should be `long`, not `int`, 

Did you make sure that you use `IdentityUser<long>` everywhere and not `IdentityUser<int>`?

**Comment by rkaule** [comment]
Sorry,  The above code was a version that I was trying.  Everywhere you see IdentityUser above should be IdentyUser<long>. That being said.  I change the code so the ReadAsync was mapping to the IdentyUser.  like:
   IdentityUser idUser = await _connection.WithCancellationToken(cancellationToken).ReadAsync<IdentityUser>(...

So Norm was mapping to the IdentityUser,  then I created an IdentityUser<long>, set the Tkey, and copied the rest of the fields and returned that.   That worked.  

I think the ReadAsync didn't like the templated class, like it thought it was to return a long instead of the IdentityUser<long>.

Thanks for creating Norm.  It's great for those of us that understand the sequel language and can control it's power.

Bob

**Comment by rkaule** [comment]
Sorry the makeup language is one that I'm not familiar with.  It keeps taking out my left and right angle brackets (and everything in between).

**Comment by vbilopav** [comment]
I'm not sure if your issue is resolved or not. Is there anything else I can help you with or I can close this issue?
